services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: inventory_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Strong!Password@123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  sqlserver_tests:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: inventory_db_tests
    ports:
      - "1434:1433"   
    environment:
      SA_PASSWORD: "Strong!Password@123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_test_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: InventoryManagement.WEB/Dockerfile
    container_name: inventory_api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - sqlserver_tests
    environment:
      ConnectionStrings__DefaultConnection: "Server=inventory_db,1433;Database=InventoryManagement;User Id=sa;Password=Strong!Password@123;TrustServerCertificate=True;"

volumes:
  sqlserver_data:
  sqlserver_test_data:
