name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запуск при пуше в master
  pull_request:
    branches:
      - master  # Запуск при PR в master
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "Strong!Password@123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: --health-cmd "exit 0" --health-interval=5s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Укажи свою версию .NET

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Wait for SQL Server to be ready
        run: sleep 15s  # Ждем пока SQL Server полностью запустится
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Run Tests 
        run: dotnet test --no-build --configuration Release --logger trx

  build:
    name: Build and Push Docker Image
    needs: test  # Запуск только если тесты пройдены
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-api:latest -f InventoryManagement.WEB/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-api:latest
